"""Turns results/results.json into manuscript-ready tables (Markdown) and figures (PNG)."""
import json, sys, os, numpy as np
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt

R = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "results/results.json"))
OUT = os.path.dirname(sys.argv[1]) if len(sys.argv) > 1 else "results"
L = []
def ms(vals, d=3): v = np.array(vals, float); return f"{v.mean():.{d}f} ± {v.std(ddof=1) if len(v) > 1 else 0:.{d}f}"
seeds = list(R["main"].keys()); models = [m for m in R["main"][seeds[0]]]

L.append("# Results generated by run_all.py\n")
a = R["data_audit"]
L.append(f"**Data audit.** Rows in CSV: {a['rows_in_csv']:,}; rows used: {a['rows_used']:,}; jurisdictions: {a['n_jurisdictions']}; "
         f"missing temperature: {100*a['temperature_missing_frac']:.2f}%; contexts: {R['n_contexts']:,}.\n")
L.append("| Year | Records |\n|---|---|\n" + "\n".join(f"| {y} | {n:,} |" for y, n in a["years"].items()) + "\n")
si = R["split_info"][seeds[0]]
L.append(f"**Split (seed {seeds[0]}).** label threshold = {si['label_threshold_count']:.0f} accidents; train/val/test = "
         f"{si['n_train']}/{si['n_val']}/{si['n_test']}; positive fraction train/val/test = "
         f"{si['pos_frac_train']:.3f}/{si['pos_frac_val']:.3f}/{si['pos_frac_test']:.3f}.\n")

L.append("## Table: main comparison (mean ± sd over seeds)\n")
L.append("| Method | Acc. | Prec. | Rec. | F1 | AUC | DeLong p (max over seeds) | McNemar p (max) |\n|---|---|---|---|---|---|---|---|")
order = sorted(models, key=lambda m: np.mean([R["main"][s][m]["auc"] for s in seeds]))
for m in order:
    row = [ms([R["main"][s][m][k] for s in seeds]) for k in ("acc", "prec", "rec", "f1", "auc")]
    if m == "FedHSA": sig = ["—", "—"]
    else: sig = [f"{max(R['significance'][s][m]['delong_p'] for s in seeds):.3g}", f"{max(R['significance'][s][m]['mcnemar']['p'] for s in seeds):.3g}"]
    L.append(f"| {m} | " + " | ".join(row + sig) + " |")
c = R["main"][seeds[0]]["FedHSA"]
L.append(f"\nFedHSA confusion matrix (seed {seeds[0]}): TP={c['tp']}, TN={c['tn']}, FP={c['fp']}, FN={c['fn']}.\n")

L.append("## Table: ablation (AUC, mean ± sd)\n\n| Variant | AUC | ΔAUC vs full |\n|---|---|---|")
full = np.mean([R["main"][s]["FedHSA"]["auc"] for s in seeds])
L.append(f"| Full FedHSA | {ms([R['main'][s]['FedHSA']['auc'] for s in seeds])} | — |")
for v in [k for k in R["ablation"][seeds[0]] if not k.startswith("_")]:
    vals = [R["ablation"][s][v]["auc"] for s in seeds]
    L.append(f"| {v} | {ms(vals)} | {100*(np.mean(vals)-full)/full:+.1f}% |")
d = R["ablation"][seeds[0]].get("_resid_diag")
if d: L.append(f"\nResidual-free diagnostic: predicted probability range [{d['prob_min']:.3f}, {d['prob_max']:.3f}], std {d['prob_std']:.4f}; train loss {d['train_loss'][0]:.3f} → {d['train_loss'][-1]:.3f}.\n")

if "sensitivity" in R:
    L.append("## Table: sensitivity (validation AUC)\n\n| Parameter | Value | Val. AUC |\n|---|---|---|")
    for p in ("alpha", "beta"):
        for v, vals in R["sensitivity"][p].items(): L.append(f"| {p} | {v} | {ms(vals)} |")
    for v, rows in R["sensitivity"]["rounds"].items():
        L.append(f"| rounds | {v} | {ms([r['val_auc'] for r in rows])} (train loss {np.mean([r['final_train_loss'] for r in rows]):.3f}) |")

if "robustness" in R:
    for key in R["robustness"]:
        L.append(f"\n## Table: robustness ({key}) — test AUC under temperature noise\n")
        sg = list(next(iter(R["robustness"][key].values()))[0].keys())
        L.append("| Model | " + " | ".join(f"σ={s}" for s in sg) + " | Drop at σ=0.2 |\n|" + "---|" * (len(sg) + 2))
        for m, rows in R["robustness"][key].items():
            means = [np.mean([r[s] for r in rows]) for s in sg]
            drop = 100 * (means[0] - np.mean([r["0.2"] for r in rows])) / means[0] if "0.2" in sg else float("nan")
            L.append(f"| {m} | " + " | ".join(f"{x:.3f}" for x in means) + f" | {drop:.1f}% |")

if "faithfulness" in R:
    F = R["faithfulness"]; feats = R["features"]
    L.append("\n## Table: attribution faithfulness\n\n| Method | Top-2 features | Kendall τ vs SHAP | AUC after removal | ΔAUC |\n|---|---|---|---|---|")
    for k, v in F["methods"].items():
        tau = "—" if v["tau_vs_shap"] is None else f"{v['tau_vs_shap']:.2f}"
        L.append(f"| {k} | {', '.join(v['top_features']) if v['top_features'] else 'random'} | {tau} | {v['auc_after_removal']:.3f} | {v['auc_after_removal']-F['full_auc']:+.3f} |")
    imp = np.array(F["importance"]["Spike rate x attention"]); cum = np.cumsum(np.sort(imp)[::-1])
    L.append("\n| Feature | Attribution | \n|---|---|\n" + "\n".join(f"| {feats[i]} | {imp[i]:.3f} |" for i in np.argsort(-imp)))

if "forward" in R:
    L.append("\n## Table: forward-chaining protocol (train < 2022, test 2022)\n\n| Method | F1 | AUC |\n|---|---|---|")
    for m in [k for k in R["forward"][seeds[0]] if not k.startswith("_")]:
        L.append(f"| {m} | {ms([R['forward'][s][m]['f1'] for s in seeds])} | {ms([R['forward'][s][m]['auc'] for s in seeds])} |")

e = R.get("efficiency", {}); env = R["environment"]
L.append(f"\n**Efficiency.** parameters={e.get('parameters')}, bytes/update={e.get('bytes_per_update')}, "
         f"inference for all contexts={1000*e.get('inference_seconds_all_contexts', float('nan')):.2f} ms.\n")
L.append(f"**Environment.** {env['platform']}; CPU: {env['processor']} ({env['cpu_count']} logical cores); Python {env['python']}; PyTorch {env['torch']}; CUDA={env['cuda']}; total runtime {R.get('total_minutes', float('nan')):.1f} min.\n")
open(os.path.join(OUT, "tables.md"), "w").write("\n".join(L))

# figures
conv = R["convergence"]; rounds = [h["round"] for h in conv[0]]
fig, ax = plt.subplots(1, 2, figsize=(9, 3.4), dpi=200)
for k, key, lab in ((0, "train_loss", "Training loss"), (1, "val_auc", "Validation AUC")):
    M = np.array([[h[key] for h in run] for run in conv]); mu, sd = M.mean(0), M.std(0)
    ax[k].plot(rounds, mu, "o-", ms=3); ax[k].fill_between(rounds, mu - sd, mu + sd, alpha=0.25); ax[k].set_xlabel("Communication round"); ax[k].set_ylabel(lab)
plt.tight_layout(); plt.savefig(os.path.join(OUT, "fig2_convergence.png")); plt.close()
print("wrote", os.path.join(OUT, "tables.md"))

# Fig. 3: attribution
if "faithfulness" in R:
    imp = np.array(R["faithfulness"]["importance"]["Spike rate x attention"]); feats = R["features"]; o = np.argsort(imp)
    fig, ax = plt.subplots(figsize=(6.5, 3.4), dpi=200); ax.barh([feats[i] for i in o], 100 * imp[o], color="#2F5D8A")
    for k, i in enumerate(o): ax.text(100 * imp[i] + 0.5, k, f"{100*imp[i]:.1f}%", va="center", fontsize=8)
    ax.set_xlabel("Normalized attribution (%)"); plt.tight_layout(); plt.savefig(os.path.join(OUT, "fig3_attribution.png")); plt.close()
# Fig. 4: robustness (no augmentation and with augmentation)
if "robustness" in R:
    keys = list(R["robustness"]); fig, axes = plt.subplots(1, len(keys), figsize=(6 * len(keys), 3.6), dpi=200, squeeze=False)
    for ax, key in zip(axes[0], keys):
        ms_ = list(R["robustness"][key]); x = np.arange(len(ms_))
        clean = [np.mean([r["0.0"] for r in R["robustness"][key][m]]) for m in ms_]
        noisy = [np.mean([r["0.2"] for r in R["robustness"][key][m]]) for m in ms_]
        ax.bar(x - .18, clean, .36, label="clean"); ax.bar(x + .18, noisy, .36, label="σ = 0.2", hatch="//")
        for i in x: ax.text(i, max(clean[i], noisy[i]) + .005, f"−{100*(clean[i]-noisy[i])/clean[i]:.1f}%", ha="center", fontsize=7)
        ax.set_xticks(x); ax.set_xticklabels(ms_, rotation=30, ha="right", fontsize=8); ax.set_ylabel("Test AUC"); ax.set_title(key.replace("_", " "), fontsize=9)
        ax.set_ylim(min(noisy) - .05, max(clean) + .04); ax.legend(fontsize=8)
    plt.tight_layout(); plt.savefig(os.path.join(OUT, "fig4_robustness.png")); plt.close()
# Fig. 5: ablation
vs = ["Full FedHSA"] + [k for k in R["ablation"][seeds[0]] if not k.startswith("_")]
vals = [[R["main"][s]["FedHSA"]["auc"] for s in seeds]] + [[R["ablation"][s][v]["auc"] for s in seeds] for v in vs[1:]]
fig, ax = plt.subplots(figsize=(7.5, 3.6), dpi=200)
ax.bar(range(len(vs)), [np.mean(v) for v in vals], yerr=[np.std(v, ddof=1) if len(v) > 1 else 0 for v in vals], capsize=3, color=["#2F5D8A"] + ["#C97B2A"] * (len(vs) - 1))
ax.axhline(0.5, ls=":", color="gray"); ax.set_xticks(range(len(vs))); ax.set_xticklabels(vs, rotation=25, ha="right", fontsize=8); ax.set_ylabel("Test AUC")
plt.tight_layout(); plt.savefig(os.path.join(OUT, "fig5_ablation.png")); plt.close()
print("figures written")
